- name: Build and Push Docker Image
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Authenticate Docker with GCP Artifact Registry
      shell: |
        gcloud auth configure-docker {{ gcp_region }}-docker.pkg.dev --quiet

    - name: Build Docker image
      shell: |
        docker build -t {{ docker_image_name }}:{{ docker_tag }} -f docker/Dockerfile.ubuntu .

    - name: Tag Docker image
      shell: |
        docker tag {{ docker_image_name }}:{{ docker_tag }} \
          {{ docker_repo }}/{{ docker_image_name }}:{{ docker_tag }}

    - name: Push Docker image
      shell: |
        docker push {{ docker_repo }}/{{ docker_image_name }}:{{ docker_tag }}
