- name: Decommission GCP Resources
  hosts: localhost
  gather_facts: false
  vars:
    sa_email: "{{ service_account_name }}@{{ gcp_project_id }}.iam.gserviceaccount.com"
  tasks:
    - name: Delete Artifact Registry (manual step if needed)
      shell: |
        gcloud artifacts repositories delete {{ gcp_artifact_repo }} \
          --location={{ gcp_region }} --project={{ gcp_project_id }} --quiet
      ignore_errors: true

    - name: Delete GCS Bucket
      shell: |
        gsutil rm -r gs://{{ gcs_bucket_name }}
      ignore_errors: true

    - name: Delete Service Account
      shell: |
        gcloud iam service-accounts delete {{ sa_email }} --quiet --project={{ gcp_project_id }}
      ignore_errors: true

    - name: Delete Secret
      shell: |
        gcloud secrets delete {{ gcp_credentials_secret_name }} --quiet --project={{ gcp_project_id }}
      ignore_errors: true
