- name: Build and push ETL Docker image
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Build Jenkins/ETL image
      community.general.docker_image:
        name: "gcp_etl_jenkins"
        tag: latest
        build:
          path: "{{ playbook_dir }}/.."
          dockerfile: docker/Dockerfile.jenkins
          pull: yes
          nocache: yes

    - name: Push ETL image
      ansible.builtin.command: >
        docker push your_registry/gcp_etl_jenkins:latest