- name: Setup GCP resources
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Call setup_gcp_resources.yml playbook
      ansible.builtin.include_tasks:
        file: ansible/playbook/setup_gcp_resources.yml

- name: Build & push Docker image to GCP Artifact Registry
  hosts: localhost
  vars:
    env: "{{ env }}"
    gcp_project_id: "{{ gcp_project_id }}"
    gcp_region: "{{ gcp_region }}"
    gcp_artifact_repo: "{{ gcp_artifact_repo }}"
    image_name: "{{ docker_image_name }}"
    image_tag: "{{ docker_tag }}"
    docker_repo: "{{ docker_repo }}"
    environment: "{{ environment }}"
    custom_var_value: "{{ custom_var_value }}"
    gcp_credentials_path: "{{ gcp_credentials_path }}"
  tasks:
    - name: Retrieve GCP credentials from Secret Manager
      gcp_secret_manager_secret:
        project_id: "{{ gcp_project_id }}"
        secret_id: "{{ gcp_credentials_secret_name }}"
        version: "latest"
      register: gcp_credentials_secret
      no_log: true

    - name: Generate .env file from Jinja template
      template:
        src: ansible/templates/.env.j2
        dest: "/tmp/.env.${{ env }}"
      vars:
        gcp_credentials_path: "{{ gcp_credentials_secret.secret_data }}"

    - name: Build Docker image
      community.general.docker_image:
        name: "{{ image_name }}"
        tag: "{{ image_tag }}"
        build:
          path: "{{ playbook_dir }}/.."
          dockerfile: "{{ docker/Dockerfile.ansible }}"
          pull: yes
          nocache: yes
          args:
            ENV_FILE: "/tmp/.env.${{ env }}"

    - name: Tag image for GCP Artifact Registry
      ansible.builtin.command: >
        docker tag {{ image_name }}:{{ image_tag }}
        {{ gcp_region }}-docker.pkg.dev/{{ gcp_project_id }}/{{ gcp_artifact_repo }}/{{ image_name }}:{{ image_tag }}

    - name: Push image to GCP Artifact Registry
      ansible.builtin.command: >
        docker push {{ gcp_region }}-docker.pkg.dev/{{ gcp_project_id }}/{{ gcp_artifact_repo }}/{{ image_name }}:{{ image_tag }}

    - name: Clean up temporary .env file
      ansible.builtin.file:
        path: "/tmp/.env.${{ env }}"
        state: absent

- name: Decommission GCP resources
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Call decom_gcp_resources.yml playbook
      ansible.builtin.include_tasks:
        file: ansible/playbook/decom_gcp_resources.yml
