# General variables for all hosts/environments

gcp_project_id: "your-gcp-project-id"
gcp_region: "us-central1"

gcp_artifact_repo: "my-etl-repo"
service_account_name: "etl-service-account"
gcs_bucket_name: "etl-gcs-bucket"

gcp_credentials_secret_name: "etl-credentials-secret"

docker_repo: "gcr.io/your-gcp-project-id"
docker_image_name: "etl_image"

docker_tag: "latest"

env: "dev"  # Default environment, override per environment or at runtime


