# General variables for all hosts/environments

gcp_project_id: "my-gcp-project-dev"
gcp_region: "us-central1"
gcp_zone: "us-central1-a"

# Artifact Registry
gcp_artifact_repo: "us-central1-docker.pkg.dev/my-gcp-project-dev/etl-artifacts"
docker_repo: "{{ gcp_artifact_repo }}"

# Docker image info
docker_image_name: "etl-app"
docker_tag: "{{ ansible_date_time.epoch | default('latest') }}"
tag: "{{ docker_tag }}"
image_tag: "{{ docker_tag }}"

# GCS Bucket
gcs_bucket_name: "my-gcp-project-dev-etl-data"
gcs_bucket_location: "us-central1"

# Service account and secrets
service_account_name: "etl-vm-sa"
service_account_display_name: "ETL VM Service Account"
gcp_credentials_secret_name: "etl-service-account-key"

# Compute instance
instance_name: "etl-vm-dev"
machine_type: "e2-micro"  # Always Free tier
boot_image: "debian-cloud/debian-11"
disk_size: "30"  # GB - within free tier limits

# Network
network_name: "data-network-dev"
subnet_name: "data-subnet-dev"
cidr_range: "10.10.0.0/16"

# Local paths and files
gcp_service_account_file: "/tmp/service-account.json"



