stage('Terraform Apply') {
    steps {
        dir("terraform/envs/${params.ENV}") {
            sh "terraform init"
            sh "terraform apply -auto-approve"
        }
    }
}

stage('Terraform Destroy') {
    when {
        expression { params.ACTION == 'destroy_infra' }
    }
    steps {
        dir("terraform/envs/${params.ENV}") {
            sh "terraform init"
            sh "terraform destroy -auto-approve"
        }
    }
}
